name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5

      - name: Install dependencies
        run: bun install

      - name: Check linter and formatter
        run: bun run ci
